github.com:
    users:
        camillanapoles:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: camillanapoles
